spring.application.name=API

#debug=false
##logging.level.root=DEBUG
##logging.level.org.springframework=DEBUG

#debug=true
#logging.level.root=DEBUG
#logging.level.org.springframework=DEBUG


spring.datasource.url=jdbc:postgresql://localhost:8040/damoDB
spring.datasource.username=postgres
spring.datasource.password=141592

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

#server.servlet.context-path=/api
